var searchData=
[
  ['xdebug',['XDebug',['../group__x_debug.html',1,'']]],
  ['xdebug_20api',['xDebug API',['../group__x_debug___exported___a_p_is.html',1,'']]],
  ['xgpio',['XGPIO',['../group__x_g_p_i_o.html',1,'']]],
  ['xgpio_20interrupt_20number_20config',['xGPIO interrupt number config',['../group__x_g_p_i_o___config.html',1,'']]],
  ['xgpio_20dir_20mode',['xGPIO Dir Mode',['../group__x_g_p_i_o___dir___mode.html',1,'']]],
  ['xgpio_20api',['xGPIO API',['../group__x_g_p_i_o___exported___a_p_is.html',1,'']]],
  ['xgpio_20general_20pin_20id',['xGPIO General Pin ID',['../group__x_g_p_i_o___general___pin___i_ds.html',1,'']]],
  ['xgpio_20general_20purpose_20short_20pin',['xGPIO General Purpose Short Pin',['../group__x_g_p_i_o___g_p___short___pin.html',1,'']]],
  ['xgpio_20int_20type',['xGPIO Int Type',['../group__x_g_p_i_o___int___type.html',1,'']]],
  ['xgpio_20pad_20config_20strength',['xGPIO Pad Config Strength',['../group__x_g_p_i_o___pad___config___strength.html',1,'']]],
  ['xgpio_20pad_20config_20type',['xGPIO Pad Config Type',['../group__x_g_p_i_o___pad___config___type.html',1,'']]],
  ['xgpio_20general_20peripheral_20pin',['xGPIO General Peripheral Pin',['../group__x_g_p_i_o___peripheral___pin.html',1,'']]],
  ['xgpio_20short_20pin_20id',['xGPIO Short Pin ID',['../group__x_g_p_i_o___short___pin.html',1,'']]],
  ['xlowlayer',['XLowLayer',['../group__x_low_layer.html',1,'']]],
  ['xlowlayer_20types',['xLowLayer Types',['../group__x_low_layer___exported___types.html',1,'']]],
  ['xlowlayer_20hardware_20access',['xLowLayer Hardware Access',['../group__x_low_layer___hardware___access.html',1,'']]],
  ['xlowlayer_20interrupt_20assignments',['xLowLayer Interrupt Assignments',['../group__x_low_layer___interrupt___assignments.html',1,'']]],
  ['xlowlayer_20peripheral_20memmap',['xLowLayer Peripheral Memmap',['../group__x_low_layer___peripheral___memmap.html',1,'']]],
  ['xspi',['XSPI',['../group__x_s_p_i.html',1,'']]],
  ['xspi_20configure',['xSPI Configure',['../group__x_s_p_i___config.html',1,'']]],
  ['xspi_20dma',['xSPI DMA',['../group__x_s_p_i___d_m_a.html',1,'']]],
  ['xspi_20api',['xSPI API',['../group__x_s_p_i___exported___a_p_is.html',1,'']]],
  ['xspi_20interrupts',['xSPI Interrupts',['../group__x_s_p_i___ints.html',1,'']]],
  ['xspi_20interrupt_20event',['xSPI Interrupt Event',['../group__x_s_p_i___ints___event.html',1,'']]],
  ['xspi_20slave_20select',['xSPI Slave Select',['../group__x_s_p_i___slave_sel.html',1,'']]],
  ['xspi_20slave_20select_20mode',['xSPI Slave Select Mode',['../group__x_s_p_i___slave_sel_mode.html',1,'']]],
  ['xsysctl',['XSysCtl',['../group__x_sys_ctl.html',1,'']]],
  ['xsysctl_20clock_20set_20configuration',['xSysCtl Clock Set Configuration',['../group__x_sys_ctl___clock___set___config.html',1,'']]],
  ['xsysctl_20api',['xSysCtl API',['../group__x_sys_ctl___exported___a_p_is.html',1,'']]],
  ['xsysctl_20peripheral_20id',['xSysCtl Peripheral ID',['../group__x_sys_ctl___peripheral___i_d.html',1,'']]]
];
